name: CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Setup gcloud CLI (install latest version to get 'gcloud builds wait')
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'

      # Step 4: Enable required APIs
      - name: Enable Required APIs
        run: |
          gcloud services enable \
            cloudbuild.googleapis.com \
            run.googleapis.com \
            sqladmin.googleapis.com \
            --project=${{ secrets.GCP_PROJECT_ID }}

      # Step 5: Build and Push Docker Image to GCR (async + wait)
      - name: Build and Push to GCR
        run: |
          BUILD_ID=$(gcloud builds submit \
            --async \
            --format='value(id)' \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --project=${{ secrets.GCP_PROJECT_ID }})

          echo "Cloud Build submitted with ID: $BUILD_ID"

          # Wait for the build to complete (requires newer gcloud)
          gcloud builds wait "$BUILD_ID" --project=${{ secrets.GCP_PROJECT_ID }}

      # Step 6: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
            --set-secrets DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest \
            --project=${{ secrets.GCP_PROJECT_ID }}
