name: Deploy to GCP (Cloud Run)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK 
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Docker to use gcloud as a credential helper
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      # Step 4: Build and push Docker image to Artifact Registry
      - name: Build and push Docker image
        run: |
          echo "Building the Docker image and pushing it to Artifact Registry..."
          docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repository/api:latest .
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repository/api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up Google Cloud SDK again in this job
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 2: Install beta components (for "gcloud beta run deploy")
      - name: Install gcloud beta components
        run: |
          gcloud components install beta --quiet

      # Step 3: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          gcloud beta run deploy my-app \
            --image=us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repository/api:latest \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --ingress=all \
            --port=8080 \
            --service-account=sa-deployment@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --min-instances=1 \
            --timeout=900s \
            --platform=managed \
            --region=us-east1 \
            --quiet
